name: Unity Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push but only for tags starting with "v" (i.e. v0.1)
  push:
    tags: v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build-webgl:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Unity - Build
        run: ./.scripts/build_webgl.bat
      
      - name: Create Archive
        run: Compress-Archive -Path ./build/* -DestinationPath ./game.zip

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: game_webgl
          path: ./game.zip
          retention-days: 9

  build-win64:
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Unity - Build
        run: ./.scripts/build_win64.bat
      
      - name: Create Archive
        run: Compress-Archive -Path ./build/* -DestinationPath ./game.zip

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: game_win64
          path: ./game.zip
          retention-days: 9

  build-osx:
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Unity - Build
        run: ./.scripts/build_osx.bat
      
      - name: Create Archive
        run: Compress-Archive -Path ./build/* -DestinationPath ./game.zip

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: game_osx
          path: ./game.zip
          retention-days: 9

  # build-linux:
  #   runs-on: self-hosted

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Unity - Build
  #       run: ./.scripts/build_linux.bat
      
  #     - name: Create Archive
  #       run: Compress-Archive -Path ./build/* -DestinationPath ./game.zip

  #     - name: Upload a Build Artifact
  #       uses: actions/upload-artifact@v2.2.2
  #       with:
  #         name: game_linux
  #         path: ./game.zip
  #         retention-days: 9
         
  deploy-webgl:
    runs-on: windows-latest
    needs: [build-webgl]
    name: Deploy to itch.io (Web)
    env:
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      itch_channel: ${{ secrets.ITCH_USERNAME }}/${{ secrets.ITCH_GAME_NAME }}:web
    steps:
      - name: Download Game Artifact
        uses: actions/download-artifact@v2.0.8
        with:
          name: game_webgl
      - name: Configure Butler
        run: |
          Invoke-WebRequest -Uri https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default -OutFile butler.zip
          Expand-Archive -Path butler.zip -DestinationPath .
          ./butler.exe -V
          ./butler.exe login
        shell: powershell
      - name: Push to itch.io
        run: ./butler.exe push ./game.zip $env:itch_channel
        shell: powershell
         
  deploy-win64:
    runs-on: windows-latest
    needs: [build-win64]
    name: Deploy to itch.io (win64)
    env:
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      itch_channel: ${{ secrets.ITCH_USERNAME }}/${{ secrets.ITCH_GAME_NAME }}:win64
    steps:
      - name: Download Game Artifact
        uses: actions/download-artifact@v2.0.8
        with:
          name: game_win64
      - name: Configure Butler
        run: |
          Invoke-WebRequest -Uri https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default -OutFile butler.zip
          Expand-Archive -Path butler.zip -DestinationPath .
          ./butler.exe -V
          ./butler.exe login
        shell: powershell
      - name: Push to itch.io
        run: ./butler.exe push ./game.zip $env:itch_channel
        shell: powershell
         
  deploy-osx:
    runs-on: windows-latest
    needs: [build-osx]
    name: Deploy to itch.io (OSX)
    env:
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      itch_channel: ${{ secrets.ITCH_USERNAME }}/${{ secrets.ITCH_GAME_NAME }}:osx
    steps:
      - name: Download Game Artifact
        uses: actions/download-artifact@v2.0.8
        with:
          name: game_osx
      - name: Configure Butler
        run: |
          Invoke-WebRequest -Uri https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default -OutFile butler.zip
          Expand-Archive -Path butler.zip -DestinationPath .
          ./butler.exe -V
          ./butler.exe login
        shell: powershell
      - name: Push to itch.io
        run: ./butler.exe push ./game.zip $env:itch_channel
        shell: powershell
         
  # deploy-linux:
  #   runs-on: windows-latest
  #   needs: [build-linux]
  #   name: Deploy to itch.io (Linux)
  #   env:
  #     BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  #     itch_channel: ${{ secrets.ITCH_USERNAME }}/${{ secrets.ITCH_GAME_NAME }}:linux
  #   steps:
  #     - name: Download Game Artifact
  #       uses: actions/download-artifact@v2.0.8
  #       with:
  #         name: game_linux
  #     - name: Configure Butler
  #       run: |
  #         Invoke-WebRequest -Uri https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default -OutFile butler.zip
  #         Expand-Archive -Path butler.zip -DestinationPath .
  #         ./butler.exe -V
  #         ./butler.exe login
  #       shell: powershell
  #     - name: Push to itch.io
  #       run: ./butler.exe push ./game.zip $env:itch_channel
  #       shell: powershell

  notify:
    runs-on: windows-latest
    needs: [deploy-webgl, deploy-win64, deploy-osx]
    name: Notify Discord
    env:
      itch_url: https://${{ secrets.ITCH_USERNAME }}.itch.io/${{ secrets.ITCH_GAME_NAME }}
    if: success() 
    steps:
      - name: Notify Discord
        run: Invoke-WebRequest -Method Post -Body @{content="New build deployed - $env:itch_url"} -Uri ${{ secrets.DISCORD_WEBHOOK_URL }}
        shell: powershell

